// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Delta represents a Quill Delta document or sequence of operations.
 */
export class Delta {
    "ops": Op[];

    /** Creates a new Delta instance. */
    constructor($$source: Partial<Delta> = {}) {
        if (!("ops" in $$source)) {
            this["ops"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Delta instance from a string or object.
     */
    static createFrom($$source: any = {}): Delta {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ops" in $$parsedSource) {
            $$parsedSource["ops"] = $$createField0_0($$parsedSource["ops"]);
        }
        return new Delta($$parsedSource as Partial<Delta>);
    }
}

/**
 * InsertData is an interface to represent the insert content.
 * It can be implemented by types representing strings or embedded objects.
 */
export type InsertData = any;

/**
 * Op represents a single operation in a Quill Delta.
 */
export class Op {
    "insert"?: InsertData;
    "delete"?: number;
    "retain"?: number;
    "attributes"?: { [_ in string]?: any };

    /** Creates a new Op instance. */
    constructor($$source: Partial<Op> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Op instance from a string or object.
     */
    static createFrom($$source: any = {}): Op {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField3_0($$parsedSource["attributes"]);
        }
        return new Op($$parsedSource as Partial<Op>);
    }
}

// Private type creation functions
const $$createType0 = Op.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
