// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    GlossaryEntry,
    Translator
} from "./models.js";

export type {
    Language
} from "./models.js";
