// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GlossaryEntry represents a term mapping for consistency across the novel.
 */
export class GlossaryEntry {
    /**
     * Original term (e.g., character name in source language)
     */
    "source": string;

    /**
     * Translated term (e.g., character name in target language)
     */
    "target": string;

    /**
     * Optional context or description of the term
     */
    "note": string;

    /** Creates a new GlossaryEntry instance. */
    constructor($$source: Partial<GlossaryEntry> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlossaryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): GlossaryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlossaryEntry($$parsedSource as Partial<GlossaryEntry>);
    }
}

/**
 * Language represents a language identifier defined in constant.go.
 */
export type Language = number;

/**
 * Translator holds the core configuration for translation style and few-shot learning.
 */
export class Translator {
    /**
     * Source language (e.g., LAN_JP)
     */
    "source_lang": Language;

    /**
     * Target language (e.g., LAN_ZH_CN)
     */
    "target_lang": Language;

    /**
     * Instructions on writing style (e.g., "Modern Chinese light novel style")
     */
    "style_prompt": string;

    /**
     * Short sample of high-quality human-translated text for few-shot learning
     */
    "template": string;

    /** Creates a new Translator instance. */
    constructor($$source: Partial<Translator> = {}) {
        if (!("source_lang" in $$source)) {
            this["source_lang"] = 0;
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = 0;
        }
        if (!("style_prompt" in $$source)) {
            this["style_prompt"] = "";
        }
        if (!("template" in $$source)) {
            this["template"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Translator instance from a string or object.
     */
    static createFrom($$source: any = {}): Translator {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Translator($$parsedSource as Partial<Translator>);
    }
}
