// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as quilldelta$0 from "../../quill-delta/quilldelta/models.js";

export class ChunkInfo {
    "delta": quilldelta$0.Delta | null;
    "translatedDelta"?: quilldelta$0.Delta | null;
    "current": number;
    "total": number;
    "unsavedChanges": boolean;
    "dirty": boolean;

    /** Creates a new ChunkInfo instance. */
    constructor($$source: Partial<ChunkInfo> = {}) {
        if (!("delta" in $$source)) {
            this["delta"] = null;
        }
        if (!("current" in $$source)) {
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("unsavedChanges" in $$source)) {
            this["unsavedChanges"] = false;
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChunkInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ChunkInfo {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("delta" in $$parsedSource) {
            $$parsedSource["delta"] = $$createField0_0($$parsedSource["delta"]);
        }
        if ("translatedDelta" in $$parsedSource) {
            $$parsedSource["translatedDelta"] = $$createField1_0($$parsedSource["translatedDelta"]);
        }
        return new ChunkInfo($$parsedSource as Partial<ChunkInfo>);
    }
}

export class TranslationEventPayload {
    "handle": string;
    "seq": number;
    "text": string;
    "error": string;
    "completed": boolean;

    /** Creates a new TranslationEventPayload instance. */
    constructor($$source: Partial<TranslationEventPayload> = {}) {
        if (!("handle" in $$source)) {
            this["handle"] = "";
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationEventPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationEventPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationEventPayload($$parsedSource as Partial<TranslationEventPayload>);
    }
}

export class TranslationResponse {
    "async": boolean;
    "handle": string;
    "translated"?: string;

    /** Creates a new TranslationResponse instance. */
    constructor($$source: Partial<TranslationResponse> = {}) {
        if (!("async" in $$source)) {
            this["async"] = false;
        }
        if (!("handle" in $$source)) {
            this["handle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationResponse($$parsedSource as Partial<TranslationResponse>);
    }
}

// Private type creation functions
const $$createType0 = quilldelta$0.Delta.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
