// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Label represents a label.
 */
export class Label {
    "pos": number[];
    "tag": string;
    "text": string;
    "translated": boolean;
    "reviewed": boolean;
    "page": string;

    /** Creates a new Label instance. */
    constructor($$source: Partial<Label> = {}) {
        if (!("pos" in $$source)) {
            this["pos"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("translated" in $$source)) {
            this["translated"] = false;
        }
        if (!("reviewed" in $$source)) {
            this["reviewed"] = false;
        }
        if (!("page" in $$source)) {
            this["page"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Label instance from a string or object.
     */
    static createFrom($$source: any = {}): Label {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Label($$parsedSource as Partial<Label>);
    }
}

export type Labels = Label[];
