// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as comic$0 from "../../../../label-go/comic/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as label$0 from "../../../../label-go/label/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class PageMeta {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "ChapterID": number;
    "filename": string;
    "format": comic$0.ImageFormat;
    "size": number[];
    "labels": label$0.Labels;

    /** Creates a new PageMeta instance. */
    constructor($$source: Partial<PageMeta> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("ChapterID" in $$source)) {
            this["ChapterID"] = 0;
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = comic$0.ImageFormat.$zero;
        }
        if (!("size" in $$source)) {
            this["size"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): PageMeta {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField8_0($$parsedSource["labels"]);
        }
        return new PageMeta($$parsedSource as Partial<PageMeta>);
    }
}

// Private type creation functions
var $$createType0 = (function $$initCreateType0(...args: any[]): any {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType2;
    }
    return $$createType0(...args);
});
const $$createType1 = label$0.Label.createFrom;
const $$createType2 = $Create.Array($$createType1);
