// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as comic$0 from "../../../../label-go/comic/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

export class PageMeta {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "ComicID": number;
    "ChapterID": number;
    "filename": string;
    "format": comic$0.ImageFormat;
    "size": number[];

    /** Creates a new PageMeta instance. */
    constructor($$source: Partial<PageMeta> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("ComicID" in $$source)) {
            this["ComicID"] = 0;
        }
        if (!("ChapterID" in $$source)) {
            this["ChapterID"] = 0;
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = comic$0.ImageFormat.$zero;
        }
        if (!("size" in $$source)) {
            this["size"] = Array.from({ length: 2 }, () => 0);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): PageMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageMeta($$parsedSource as Partial<PageMeta>);
    }
}
