//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../../../../syriku/transmas/agents/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "translation-stream": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = agents$0.TranslationEventPayload.createFrom;

configure();
