// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../aisdk/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../../aisdk/request/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as quilldelta$0 from "../../quill-delta/quilldelta/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../agents/database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as meta$0 from "../agents/meta/models.js";

export function AddChapter(projectName: string, order: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(1975024133, projectName, order, title);
}

export function AddProject(title: string): $CancellablePromise<void> {
    return $Call.ByID(2282190357, title);
}

export function CancelTranslation(handle: string): $CancellablePromise<void> {
    return $Call.ByID(2021909118, handle);
}

export function CreateReusableTranslator(projectName: string, model: string): $CancellablePromise<number> {
    return $Call.ByID(62254862, projectName, model);
}

export function DestroyReusableTranslator(handle: number): $CancellablePromise<void> {
    return $Call.ByID(3949364470, handle);
}

export function ExportTranslatedChapter(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(516328102, filePath);
}

export function GetAiConfig(): $CancellablePromise<{ [_ in string]?: api$0.UserConfig }> {
    return $Call.ByID(356686743).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetChapterMeta(): $CancellablePromise<meta$0.ChapterMeta | null> {
    return $Call.ByID(2654027689).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetChapterStatus(projectName: string, chapterOrder: number): $CancellablePromise<meta$0.ChapterStatus> {
    return $Call.ByID(1598387270, projectName, chapterOrder);
}

export function GetGlossary(projectName: string): $CancellablePromise<request$0.GlossaryEntry[]> {
    return $Call.ByID(1071380111, projectName).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetProjectAiConfigKey(projectName: string): $CancellablePromise<string> {
    return $Call.ByID(3193348911, projectName);
}

export function GetProjectTranslatorKey(projectName: string): $CancellablePromise<string> {
    return $Call.ByID(3532588269, projectName);
}

export function GetTranslationEventName(): $CancellablePromise<string> {
    return $Call.ByID(3880560773);
}

export function GetTranslators(): $CancellablePromise<{ [_ in string]?: request$0.Translator }> {
    return $Call.ByID(3337190390).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListChapters(projectName: string): $CancellablePromise<database$0.Chapter[]> {
    return $Call.ByID(3084619811, projectName).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListProjects(): $CancellablePromise<database$0.ProjectInfo[]> {
    return $Call.ByID(2606958311).then(($result: any) => {
        return $$createType11($result);
    });
}

export function LogIn(username: string): $CancellablePromise<void> {
    return $Call.ByID(2049314798, username);
}

export function NextChunk(): $CancellablePromise<agents$0.ChunkInfo> {
    return $Call.ByID(1364276089).then(($result: any) => {
        return $$createType12($result);
    });
}

export function PrevChunk(): $CancellablePromise<agents$0.ChunkInfo> {
    return $Call.ByID(2069210457).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ReadChapter(projectName: string, chapterOrder: number, force: boolean): $CancellablePromise<agents$0.ChunkInfo> {
    return $Call.ByID(3756451582, projectName, chapterOrder, force).then(($result: any) => {
        return $$createType12($result);
    });
}

export function RenameProject(oldTitle: string, newTitle: string): $CancellablePromise<void> {
    return $Call.ByID(265236852, oldTitle, newTitle);
}

export function SaveChapter(): $CancellablePromise<void> {
    return $Call.ByID(1870360777);
}

export function SetCurrentChunkReviewed(completed: boolean): $CancellablePromise<void> {
    return $Call.ByID(446927088, completed);
}

export function SetCurrentChunkTranslated(completed: boolean): $CancellablePromise<void> {
    return $Call.ByID(3495825867, completed);
}

export function TranslateWithHandle(handle: number, detailed: boolean): $CancellablePromise<agents$0.TranslationResponse> {
    return $Call.ByID(167231147, handle, detailed).then(($result: any) => {
        return $$createType13($result);
    });
}

export function TranslateWithParams(projectName: string, model: string, detailed: boolean): $CancellablePromise<agents$0.TranslationResponse> {
    return $Call.ByID(3255012235, projectName, model, detailed).then(($result: any) => {
        return $$createType13($result);
    });
}

export function UpdateAiConfig(aiConfig: { [_ in string]?: api$0.UserConfig }): $CancellablePromise<void> {
    return $Call.ByID(1986688736, aiConfig);
}

export function UpdateChapterTitle(projectName: string, order: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(2236579441, projectName, order, title);
}

export function UpdateGlossary(projectName: string, glossary: request$0.GlossaryEntry[]): $CancellablePromise<void> {
    return $Call.ByID(766773864, projectName, glossary);
}

export function UpdateOriginalChunk(newDelta: quilldelta$0.Delta | null): $CancellablePromise<void> {
    return $Call.ByID(4124787660, newDelta);
}

export function UpdateProjectAiConfigKey(projectName: string, configKey: string): $CancellablePromise<void> {
    return $Call.ByID(1110364620, projectName, configKey);
}

export function UpdateProjectDir(title: string, dir: string): $CancellablePromise<void> {
    return $Call.ByID(855438220, title, dir);
}

export function UpdateProjectTranslatorKey(projectName: string, translatorKey: string): $CancellablePromise<void> {
    return $Call.ByID(3305035630, projectName, translatorKey);
}

export function UpdateTranslatedChunk(newDelta: quilldelta$0.Delta | null): $CancellablePromise<void> {
    return $Call.ByID(3975181163, newDelta);
}

export function UpdateTranslators(translators: { [_ in string]?: request$0.Translator }): $CancellablePromise<void> {
    return $Call.ByID(2132290095, translators);
}

// Private type creation functions
const $$createType0 = api$0.UserConfig.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = meta$0.ChapterMeta.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = request$0.GlossaryEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = request$0.Translator.createFrom;
const $$createType7 = $Create.Map($Create.Any, $$createType6);
const $$createType8 = database$0.Chapter.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = database$0.ProjectInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = agents$0.ChunkInfo.createFrom;
const $$createType13 = agents$0.TranslationResponse.createFrom;
