// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AgentService from "./agentservice.js";
import * as SystemService from "./systemservice.js";
export {
    AgentService,
    SystemService
};
