// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../aisdk/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../../aisdk/request/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as loader$0 from "../../kakuyomu-loader/models.js";

export function GetLanguagesMap(): $CancellablePromise<{ [_ in request$0.Language]?: string }> {
    return $Call.ByID(2561332342).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetModels retrieves a list of models using the provided UserConfig.
 */
export function GetModels(config: api$0.UserConfig): $CancellablePromise<string[]> {
    return $Call.ByID(1148362899, config).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSystemLanguage(): $CancellablePromise<string> {
    return $Call.ByID(2136166974);
}

export function ListCandidateChapters(dir: string): $CancellablePromise<string[]> {
    return $Call.ByID(4243064222, dir).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadWebNovel(url: string): $CancellablePromise<loader$0.Novel | null> {
    return $Call.ByID(1044756891, url).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SaveNovelTxt(dirPath: string, novel: loader$0.Novel | null): $CancellablePromise<void> {
    return $Call.ByID(246393112, dirPath, novel);
}

export function SetWorkDir(): $CancellablePromise<string> {
    return $Call.ByID(1417197123);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = loader$0.Novel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
