// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../../aisdk/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../../aisdk/request/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as loader$0 from "../../kakuyomu-loader/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../../../../net/http/models.js";

export function DeleteUserData(): $CancellablePromise<void> {
    return $Call.ByID(1648938747);
}

/**
 * GetAssetHandler initializes the master router with the fallback handler and returns it.
 */
export function GetAssetHandler(fallback: http$0.Handler): $CancellablePromise<http$0.Handler> {
    return $Call.ByID(900726805, fallback);
}

/**
 * GetChapterPages lists the image files (.jpg, .jpeg, .png) in the specified chapter folder.
 */
export function GetChapterPages(chapterName: string): $CancellablePromise<string[]> {
    return $Call.ByID(2223825478, chapterName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetLanguagesMap(): $CancellablePromise<{ [_ in request$0.Language]?: string }> {
    return $Call.ByID(2561332342).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetModels retrieves a list of models using the provided UserConfig.
 */
export function GetModels(config: api$0.UserConfig): $CancellablePromise<string[]> {
    return $Call.ByID(1148362899, config).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetSystemLanguage(): $CancellablePromise<string> {
    return $Call.ByID(2136166974);
}

/**
 * GetWorkspace retrieves the current workspace path.
 */
export function GetWorkspace(): $CancellablePromise<string> {
    return $Call.ByID(3257836510);
}

export function ListCandidateChapters(dir: string, isComic: boolean): $CancellablePromise<string[]> {
    return $Call.ByID(4243064222, dir, isComic).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListCandidatePages lists candidate image pages in the specified directory.
 */
export function ListCandidatePages(dir: string): $CancellablePromise<string[]> {
    return $Call.ByID(346912636, dir).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LoadWebNovel(url: string): $CancellablePromise<loader$0.Novel | null> {
    return $Call.ByID(1044756891, url).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SaveNovelTxt(dirPath: string, novel: loader$0.Novel | null): $CancellablePromise<string> {
    return $Call.ByID(246393112, dirPath, novel);
}

export function SetWorkDir(): $CancellablePromise<string> {
    return $Call.ByID(1417197123);
}

/**
 * SetWorkspace updates the workspace directory for the routing server.
 */
export function SetWorkspace(workspace: string): $CancellablePromise<void> {
    return $Call.ByID(2924081106, workspace);
}

/**
 * SortPagesNatural sorts the given list of pages naturally (alphanumeric sorting).
 */
export function SortPagesNatural(pages: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(965215698, pages).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = loader$0.Novel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
