// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChapterMeta {
    "projectName": string;
    "chapterOrder": number;
    "chapterTitle": string;
    "lastChunkSize": number;
    "lastChunkCount": number;

    /**
     * 1-based indices
     */
    "translatedChunks": number[];

    /**
     * 1-based indices
     */
    "reviewedChunks": number[];

    /** Creates a new ChapterMeta instance. */
    constructor($$source: Partial<ChapterMeta> = {}) {
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("chapterOrder" in $$source)) {
            this["chapterOrder"] = 0;
        }
        if (!("chapterTitle" in $$source)) {
            this["chapterTitle"] = "";
        }
        if (!("lastChunkSize" in $$source)) {
            this["lastChunkSize"] = 0;
        }
        if (!("lastChunkCount" in $$source)) {
            this["lastChunkCount"] = 0;
        }
        if (!("translatedChunks" in $$source)) {
            this["translatedChunks"] = [];
        }
        if (!("reviewedChunks" in $$source)) {
            this["reviewedChunks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChapterMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ChapterMeta {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("translatedChunks" in $$parsedSource) {
            $$parsedSource["translatedChunks"] = $$createField5_0($$parsedSource["translatedChunks"]);
        }
        if ("reviewedChunks" in $$parsedSource) {
            $$parsedSource["reviewedChunks"] = $$createField6_0($$parsedSource["reviewedChunks"]);
        }
        return new ChapterMeta($$parsedSource as Partial<ChapterMeta>);
    }
}

export enum ChapterStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatusUncompleted = 0,
    StatusTranslated = 1,
    StatusReviewed = 2,
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
