// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Novel represents a parsed novel chapter.
 */
export class Novel {
    "Title": string;
    "Content": string;
    "Vocabulary": { [_ in string]?: string };

    /** Creates a new Novel instance. */
    constructor($$source: Partial<Novel> = {}) {
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("Vocabulary" in $$source)) {
            this["Vocabulary"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Novel instance from a string or object.
     */
    static createFrom($$source: any = {}): Novel {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Vocabulary" in $$parsedSource) {
            $$parsedSource["Vocabulary"] = $$createField2_0($$parsedSource["Vocabulary"]);
        }
        return new Novel($$parsedSource as Partial<Novel>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
