// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../../../aisdk/request/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class Chapter {
    "Order": number;
    "Title": string;
    "Project": number;

    /** Creates a new Chapter instance. */
    constructor($$source: Partial<Chapter> = {}) {
        if (!("Order" in $$source)) {
            this["Order"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Project" in $$source)) {
            this["Project"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chapter instance from a string or object.
     */
    static createFrom($$source: any = {}): Chapter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chapter($$parsedSource as Partial<Chapter>);
    }
}

export class ProjectInfo {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "Title": string;
    "Owner": string;
    "WorkDir": string;
    "Glossary": request$0.GlossaryEntry[];
    "TranslatorKey": string;
    "AiConfigKey": string;
    "ProjectType": ProjectType;

    /** Creates a new ProjectInfo instance. */
    constructor($$source: Partial<ProjectInfo> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Owner" in $$source)) {
            this["Owner"] = "";
        }
        if (!("WorkDir" in $$source)) {
            this["WorkDir"] = "";
        }
        if (!("Glossary" in $$source)) {
            this["Glossary"] = [];
        }
        if (!("TranslatorKey" in $$source)) {
            this["TranslatorKey"] = "";
        }
        if (!("AiConfigKey" in $$source)) {
            this["AiConfigKey"] = "";
        }
        if (!("ProjectType" in $$source)) {
            this["ProjectType"] = ProjectType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectInfo {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Glossary" in $$parsedSource) {
            $$parsedSource["Glossary"] = $$createField7_0($$parsedSource["Glossary"]);
        }
        return new ProjectInfo($$parsedSource as Partial<ProjectInfo>);
    }
}

export enum ProjectType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ProjectTypeNovel = 0,
    ProjectTypeComic = 1,
};

// Private type creation functions
const $$createType0 = request$0.GlossaryEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
