// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export type ApiType = number;

export class UserConfig {
    "provider": string;
    "type": ApiType;
    "api_key": string;

    /** Creates a new UserConfig instance. */
    constructor($$source: Partial<UserConfig> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = 0;
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): UserConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserConfig($$parsedSource as Partial<UserConfig>);
    }
}
